### ISSUE TITLE
Move official GitHub repo to https://github.com/hackerinnen organization

### ISSUE THREAD

**Issue by das-g** [hackerinnen/hackerinnen#103]
Cool would be https://github.com/hackerinnen/space, IMO 🤩

**Comment by normade** [comment]
@das-g yes, definitely true :-) We didn't want to rename the repo at this point, we are afraid of causing confusion for people who already forked or checkout out the repo and broken links. Any ideas?

**Comment by das-g** [comment]
I believe if you use the action available in the settings on GitHub to move the repo to the group account, GitHub will automatically install some redirections for both the web interface and for https and ssh access to the repo. So if you want to move the repo, use that way, rather than re-uploading it. (Using the action in the GitHub interface will also take along the issue tracker with all of its issues, the wiki and all other things associated with the repository.)

Off course, those redirections will be gone again as soon as you re-use the original repo address, e.g. for your own personal clone of the authoritative repo, as the respective old URLs will then have to point to that new repo.
